# countries.py
"""
This module provides a list of countries and their ISO Alpha-2 codes.
You can import and use them for dropdowns, lookups, etc.
"""

COUNTRY_DATA = [
    {"name": "Afghanistan", "alpha2": "AF"},
    {"name": "Albania", "alpha2": "AL"},
    {"name": "Algeria", "alpha2": "DZ"},
    {"name": "Andorra", "alpha2": "AD"},
    {"name": "Angola", "alpha2": "AO"},
    {"name": "Antigua and Barbuda", "alpha2": "AG"},
    {"name": "Argentina", "alpha2": "AR"},
    {"name": "Armenia", "alpha2": "AM"},
    {"name": "Australia", "alpha2": "AU"},
    {"name": "Austria", "alpha2": "AT"},
    {"name": "Azerbaijan", "alpha2": "AZ"},
    {"name": "Bahamas", "alpha2": "BS"},
    {"name": "Bahrain", "alpha2": "BH"},
    {"name": "Bangladesh", "alpha2": "BD"},
    {"name": "Barbados", "alpha2": "BB"},
    {"name": "Belarus", "alpha2": "BY"},
    {"name": "Belgium", "alpha2": "BE"},
    {"name": "Belize", "alpha2": "BZ"},
    {"name": "Benin", "alpha2": "BJ"},
    {"name": "Bhutan", "alpha2": "BT"},
    {"name": "Bolivia", "alpha2": "BO"},
    {"name": "Bosnia and Herzegovina", "alpha2": "BA"},
    {"name": "Botswana", "alpha2": "BW"},
    {"name": "Brazil", "alpha2": "BR"},
    {"name": "Brunei Darussalam", "alpha2": "BN"},
    {"name": "Bulgaria", "alpha2": "BG"},
    {"name": "Burkina Faso", "alpha2": "BF"},
    {"name": "Burundi", "alpha2": "BI"},
    {"name": "Côte d'Ivoire", "alpha2": "CI"},
    {"name": "Cabo Verde", "alpha2": "CV"},
    {"name": "Cambodia", "alpha2": "KH"},
    {"name": "Cameroon", "alpha2": "CM"},
    {"name": "Canada", "alpha2": "CA"},
    {"name": "Central African Republic", "alpha2": "CF"},
    {"name": "Chad", "alpha2": "TD"},
    {"name": "Chile", "alpha2": "CL"},
    {"name": "China", "alpha2": "CN"},
    {"name": "Colombia", "alpha2": "CO"},
    {"name": "Comoros", "alpha2": "KM"},
    {"name": "Congo, Democratic Republic of the", "alpha2": "CD"},
    {"name": "Congo, Republic of the", "alpha2": "CG"},
    {"name": "Costa Rica", "alpha2": "CR"},
    {"name": "Croatia", "alpha2": "HR"},
    {"name": "Cuba", "alpha2": "CU"},
    {"name": "Cyprus", "alpha2": "CY"},
    {"name": "Czech Republic", "alpha2": "CZ"},
    {"name": "Denmark", "alpha2": "DK"},
    {"name": "Djibouti", "alpha2": "DJ"},
    {"name": "Dominica", "alpha2": "DM"},
    {"name": "Dominican Republic", "alpha2": "DO"},
    {"name": "Ecuador", "alpha2": "EC"},
    {"name": "Egypt", "alpha2": "EG"},
    {"name": "El Salvador", "alpha2": "SV"},
    {"name": "Equatorial Guinea", "alpha2": "GQ"},
    {"name": "Eritrea", "alpha2": "ER"},
    {"name": "Estonia", "alpha2": "EE"},
    {"name": "Eswatini", "alpha2": "SZ"},
    {"name": "Ethiopia", "alpha2": "ET"},
    {"name": "Fiji", "alpha2": "FJ"},
    {"name": "Finland", "alpha2": "FI"},
    {"name": "France", "alpha2": "FR"},
    {"name": "Gabon", "alpha2": "GA"},
    {"name": "Gambia", "alpha2": "GM"},
    {"name": "Georgia", "alpha2": "GE"},
    {"name": "Germany", "alpha2": "DE"},
    {"name": "Ghana", "alpha2": "GH"},
    {"name": "Greece", "alpha2": "GR"},
    {"name": "Grenada", "alpha2": "GD"},
    {"name": "Guatemala", "alpha2": "GT"},
    {"name": "Guinea", "alpha2": "GN"},
    {"name": "Guinea-Bissau", "alpha2": "GW"},
    {"name": "Guyana", "alpha2": "GY"},
    {"name": "Haiti", "alpha2": "HT"},
    {"name": "Honduras", "alpha2": "HN"},
    {"name": "Hungary", "alpha2": "HU"},
    {"name": "Iceland", "alpha2": "IS"},
    {"name": "India", "alpha2": "IN"},
    {"name": "Indonesia", "alpha2": "ID"},
    {"name": "Iran", "alpha2": "IR"},
    {"name": "Iraq", "alpha2": "IQ"},
    {"name": "Ireland", "alpha2": "IE"},
    {"name": "Israel", "alpha2": "IL"},
    {"name": "Italy", "alpha2": "IT"},
    {"name": "Jamaica", "alpha2": "JM"},
    {"name": "Japan", "alpha2": "JP"},
    {"name": "Jordan", "alpha2": "JO"},
    {"name": "Kazakhstan", "alpha2": "KZ"},
    {"name": "Kenya", "alpha2": "KE"},
    {"name": "Kiribati", "alpha2": "KI"},
    {"name": "Korea, North", "alpha2": "KP"},
    {"name": "Korea, South", "alpha2": "KR"},
    {"name": "Kosovo", "alpha2": "XK"},  # Unofficial but used by some systems
    {"name": "Kuwait", "alpha2": "KW"},
    {"name": "Kyrgyzstan", "alpha2": "KG"},
    {"name": "Laos", "alpha2": "LA"},
    {"name": "Latvia", "alpha2": "LV"},
    {"name": "Lebanon", "alpha2": "LB"},
    {"name": "Lesotho", "alpha2": "LS"},
    {"name": "Liberia", "alpha2": "LR"},
    {"name": "Libya", "alpha2": "LY"},
    {"name": "Liechtenstein", "alpha2": "LI"},
    {"name": "Lithuania", "alpha2": "LT"},
    {"name": "Luxembourg", "alpha2": "LU"},
    {"name": "North Macedonia", "alpha2": "MK"},
    {"name": "Madagascar", "alpha2": "MG"},
    {"name": "Malawi", "alpha2": "MW"},
    {"name": "Malaysia", "alpha2": "MY"},
    {"name": "Maldives", "alpha2": "MV"},
    {"name": "Mali", "alpha2": "ML"},
    {"name": "Malta", "alpha2": "MT"},
    {"name": "Marshall Islands", "alpha2": "MH"},
    {"name": "Mauritania", "alpha2": "MR"},
    {"name": "Mauritius", "alpha2": "MU"},
    {"name": "Mexico", "alpha2": "MX"},
    {"name": "Moldova", "alpha2": "MD"},
    {"name": "Monaco", "alpha2": "MC"},
    {"name": "Mongolia", "alpha2": "MN"},
    {"name": "Montenegro", "alpha2": "ME"},
    {"name": "Morocco", "alpha2": "MA"},
    {"name": "Mozambique", "alpha2": "MZ"},
    {"name": "Myanmar (Burma)", "alpha2": "MM"},
    {"name": "Namibia", "alpha2": "NA"},
    {"name": "Nauru", "alpha2": "NR"},
    {"name": "Nepal", "alpha2": "NP"},
    {"name": "Netherlands", "alpha2": "NL"},
    {"name": "New Zealand", "alpha2": "NZ"},
    {"name": "Nicaragua", "alpha2": "NI"},
    {"name": "Niger", "alpha2": "NE"},
    {"name": "Nigeria", "alpha2": "NG"},
    {"name": "Norway", "alpha2": "NO"},
    {"name": "Oman", "alpha2": "OM"},
    {"name": "Pakistan", "alpha2": "PK"},
    {"name": "Palau", "alpha2": "PW"},
    {"name": "Panama", "alpha2": "PA"},
    {"name": "Papua New Guinea", "alpha2": "PG"},
    {"name": "Paraguay", "alpha2": "PY"},
    {"name": "Peru", "alpha2": "PE"},
    {"name": "Philippines", "alpha2": "PH"},
    {"name": "Poland", "alpha2": "PL"},
    {"name": "Portugal", "alpha2": "PT"},
    {"name": "Qatar", "alpha2": "QA"},
    {"name": "Romania", "alpha2": "RO"},
    {"name": "Russia", "alpha2": "RU"},
    {"name": "Rwanda", "alpha2": "RW"},
    {"name": "St Kitts and Nevis", "alpha2": "KN"},
    {"name": "St Lucia", "alpha2": "LC"},
    {"name": "St Vincent and the Grenadines", "alpha2": "VC"},
    {"name": "Samoa", "alpha2": "WS"},
    {"name": "San Marino", "alpha2": "SM"},
    {"name": "Sao Tome and Principe", "alpha2": "ST"},
    {"name": "Saudi Arabia", "alpha2": "SA"},
    {"name": "Senegal", "alpha2": "SN"},
    {"name": "Serbia", "alpha2": "RS"},
    {"name": "Seychelles", "alpha2": "SC"},
    {"name": "Sierra Leone", "alpha2": "SL"},
    {"name": "Singapore", "alpha2": "SG"},
    {"name": "Slovakia", "alpha2": "SK"},
    {"name": "Slovenia", "alpha2": "SI"},
    {"name": "Solomon Islands", "alpha2": "SB"},
    {"name": "Somalia", "alpha2": "SO"},
    {"name": "South Africa", "alpha2": "ZA"},
    {"name": "South Sudan", "alpha2": "SS"},
    {"name": "Spain", "alpha2": "ES"},
    {"name": "Sri Lanka", "alpha2": "LK"},
    {"name": "Sudan", "alpha2": "SD"},
    {"name": "Suriname", "alpha2": "SR"},
    {"name": "Sweden", "alpha2": "SE"},
    {"name": "Switzerland", "alpha2": "CH"},
    {"name": "Syria", "alpha2": "SY"},
    {"name": "Taiwan", "alpha2": "TW"},
    {"name": "Tajikistan", "alpha2": "TJ"},
    {"name": "Tanzania", "alpha2": "TZ"},
    {"name": "Thailand", "alpha2": "TH"},
    {"name": "Timor-Leste", "alpha2": "TL"},
    {"name": "Togo", "alpha2": "TG"},
    {"name": "Tonga", "alpha2": "TO"},
    {"name": "Trinidad and Tobago", "alpha2": "TT"},
    {"name": "Tunisia", "alpha2": "TN"},
    {"name": "Turkey", "alpha2": "TR"},
    {"name": "Turkmenistan", "alpha2": "TM"},
    {"name": "Tuvalu", "alpha2": "TV"},
    {"name": "Uganda", "alpha2": "UG"},
    {"name": "Ukraine", "alpha2": "UA"},
    {"name": "United Arab Emirates", "alpha2": "AE"},
    {"name": "United Kingdom", "alpha2": "GB"},
    {"name": "United States", "alpha2": "US"},
    {"name": "Uruguay", "alpha2": "UY"},
    {"name": "Uzbekistan", "alpha2": "UZ"},
    {"name": "Vanuatu", "alpha2": "VU"},
    {"name": "Venezuela", "alpha2": "VE"},
    {"name": "Vietnam", "alpha2": "VN"},
    {"name": "Yemen", "alpha2": "YE"},
    {"name": "Zambia", "alpha2": "ZM"},
    {"name": "Zimbabwe", "alpha2": "ZW"}
]

def get_country_code(country_name: str) -> str:
    """
    Given a country name, returns the 2-letter ISO alpha2 code (like 'US' or 'GB').
    Returns an empty string if not found in the list.
    """
    # Basic approach: look for exact match in the dictionary
    for entry in COUNTRY_DATA:
        if entry["name"].lower().strip() == country_name.lower().strip():
            return entry["alpha2"]
    return ""  # Fallback if not found
