[server]
maxMessageSize = 200
headless = true
enableXsrfProtection = false
enableCORS = false
connectTimeout = 60  # Add timeout settings

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false

[theme]
base = "light"

[runner]
fastReruns = false